# Generated by Django 3.2.9 on 2021-11-11 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_no_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 49, 0, 211135, tzinfo=utc)),
        ),
    ]
